name: Go Test
# 触发事件
on: [push, pull_request]

# 主体
jobs:
  helloci-build:
    name: Test with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: helloci

    # 准备一个go环境
    strategy:
      matrix:
        go_version: [1.16]
        os: [ubuntu-latest]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
        id: go
        # 下载代码
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        # go mod tidy 把依赖包搞好
      - name: Tidy
        run: |
          go mod tidy
        # go build 编译
      - name: Build
        run: |
          go build -v -o helloci .
        # 上传main.go
      - name: Collect main.go file
        uses: actions/upload-artifact@v1.0.0
        with:
          name: main-output
          path: main.go
        # 镜像push
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-GitHub-Action@master
        with:
          name: registry.cn-shanghai.aliyuncs.com/luyuqiuchen/helloic:beta  # docker image 的名字
          username: ${{ secrets.DOCKER_USERNAME}} # 用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # 密码
          registry: registry.cn-shanghai.aliyuncs.com #
          dockerfile: Dockerfile # 指定 Dockerfile 的位置
          tag_names: true # 是否将 release 的 tag 作为 docker image 的 tag